-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, round(avg(B.REVIEW_SCORE) , 2) as SCORE
from REST_INFO A inner join REST_REVIEW B
on A.REST_ID = B.REST_ID
where A.ADDRESS like '서울%'
group by REST_ID
order by SCORE desc, FAVORITES desc

# A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, round(avg(B.REVIEW_SCORE) , 3) as SCORE